### ISSUE TITLE
Export broken with some studies

### ISSUE THREAD

**Issue by leonardorame** [nroduit/Weasis#185]
Hi, I found the File->Export->Dicom->Local Device option cannot handle some studies.

This case was tested with 2.6.2, 3.0.1 and 3.7.0 with two CT Coronary studies.

Both studies have many series, and some of those series more than 1000 images. I can view all the images without issues, but the Export Dicom option does now show the series tree correctly.

Here's what is shown on that option, the date on one node, a series called "2.0" wich is a Localizer, then another node with the Patient name, a subnode with the date and a 3rd node with one series with one image, but all other (more than 10) series are not shown.

![image](https://user-images.githubusercontent.com/1405017/111225678-dcd29200-85be-11eb-9be8-2ce3bf8a97d8.png)

@nroduit, I can provide a link (by email) to the URL to that study if you need.

**Comment by leonardorame** [comment]
If I uncheck "Download all series immediately" from the Preferences->Series downloader menu and re-open the study I can see the correct series structure, but of course with 0 instances.

![image](https://user-images.githubusercontent.com/1405017/111229770-448bdb80-85c5-11eb-8b19-0daed5832d0c.png)

If I click on the green triangle to start downloading then the Export screen is broken again.

**Comment by nroduit** [comment]
Do you have errors in the log file?
If you can send me an example of data that can reproduce the problem.

**Comment by leonardorame** [comment]
I've sent an email with an URL for accessing the sample data.

**Comment by nroduit** [comment]
The problem appears because the name in xml and the name in DICOM file are different. You should fix the error in the xml you provide. The unique behavior of a patient is defined [here](https://github.com/nroduit/Weasis/blob/master/weasis-dicom/weasis-dicom-codec/src/main/java/org/weasis/dicom/codec/utils/PatientComparator.java#L91-L105).

There is an mechanism to fix inconsistent ID within a study but in this case sometimes it doesn't work. I will check that later.

**Comment by leonardorame** [comment]
Hi Nicolas, I modified PatientName and PatientId on the XML to match exactly the `0010,0010` and `0010,0020` tags of the images, but sadly the problem is still present.

If you re-open the example I've sent by email the xml data you'll get contains the modified PatientName and PatientId.

**Comment by nroduit** [comment]
I guess it is something related with the xml manifest because when loading the images locally the export tree is correct.

I don't have time to check that now, but I will handle this bug later.

**Comment by leonardorame** [comment]
Yes, it might be related to the xml manifest generated automatically _for this specific study_, because all other CTs and MRs doesn't present this behavior.

**Comment by leonardorame** [comment]
Hi again Nicolas, I configured Weasis to do a Query/Retrieve of that study, so no XML is used and the problem is present also present in that configuration.

**Comment by leonardorame** [comment]
I've sent you an email with an access to a simplified XML that let you open the study with only on series (the localizer) that looks like the root of the problem.

**Comment by nroduit** [comment]
The StudyInstanceUID in the manifest does not match the one in the file. It is difficult to fix this problem because it exists in 2 detached asynchronous processes and UIDs are used as a unique key in the in-memory database.

I provided an improvement for those inconsistent UIDs, see https://github.com/nroduit/Weasis/issues/186

**Comment by leonardorame** [comment]
Thanks, now it works as expected.

The only issue now is the text in the green rectangle that I assume was left for debugging purpouses.

![image](https://user-images.githubusercontent.com/1405017/111882922-0c0a4a00-8997-11eb-9239-78eba7ebfa31.png)

BTW, I can easily fix the wrong StudyInstanceUID from the manifest, then try again with 3.7.0.

**Comment by nroduit** [comment]
No this is the consequence of the UID mismatch. I didn't find a solution without either breaking download or removing part of thumbnails.
Study/series/instance UID are the most important elements of the DCOM file structure. So they cannot be incorrect.

**Comment by nroduit** [comment]
Please reopen this issue if it has not been resolved in the current version.

See also https://github.com/nroduit/Weasis/issues/186 and https://github.com/nroduit/Weasis/issues/254
