### ISSUE TITLE
4.2.0 .rpm does not install on Fedora 38, looking for already installed dependencies 

### ISSUE THREAD

**Issue by unsafeunaudited** [nroduit/Weasis#467]
### Describe the bug. What happened?

I tried to install the .rpm version on Fedora 38 Workstation via the GUI Software Center and it gives out an error. Not sure if this is a typo of sorts because I have both libgcc and libstdc++ already installed.

### What version of Weasis are you running?

4.2.0

### On which system the problem occurs?

Linux

### Relevant log output

```shell
Could not depsolve transaction; 1 problem detected:
 Problem: conflicting requests
  - nothing provides libgcc1 needed by weasis-4.2.0-1.x86_64 from @commandline
  - nothing provides libstdc++6 needed by weasis-4.2.0-1.x86_64 from @commandline
```

### Additional contextual elements

OS: Fedora 38 Workstation
Linux Kernel Version: 6.4.14-200.fc38.x86_64
Type of installer: .rpm
Graphics: NVIDIA GeForce RTX™ 3050 Laptop GPU / AMD Radeon™ Graphics (currently using wayland as compositor)
Open GL version (as returned by <glxinfo | grep "OpenGL"> ):
OpenGL vendor string: AMD
OpenGL renderer string: AMD Radeon Graphics (renoir, LLVM 16.0.6, DRM 3.52, 6.4.14-200.fc38.x86_64)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 23.1.6
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6 (Compatibility Profile) Mesa 23.1.6
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 23.1.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:

**Comment by nroduit** [comment]
I've modified the RPM package dependencies, removing those that differ between OpenSUSE and Fedora. I've added a note describing the required packages on the download page.

You can re-download the 4.2.0 package, which should work now.

Note that it's also possible to install Weasis using Flathub or Snap.

**Comment by unsafeunaudited** [comment]
Sorry for the late reply but I redownloaded the package and it installs normally now.

The flatpak still doesnt work with Wayland but works ok with Xorg.

**Comment by dag55** [comment]
The same issue in v.4.2.1 and Fedora 39.

**Comment by nroduit** [comment]
The dependencies patch had not been applied to the build. Can you re-download the 4.2.1 package.
